/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as RecordRouteImport } from './routes/record'
import { Route as CourseSlugIndexRouteImport } from './routes/course/$slug/index'
import { Route as CourseSlugCompleteRouteImport } from './routes/course/$slug/complete'
import { Route as CourseSlugLearnRouteImport } from './routes/course/$slug/learn'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseSlugIndexRoute = CourseSlugIndexRouteImport.update({
  id: '/course/$slug/',
  path: '/course/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseSlugCompleteRoute = CourseSlugCompleteRouteImport.update({
  id: '/course/$slug/complete',
  path: '/course/$slug/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseSlugLearnRoute = CourseSlugLearnRouteImport.update({
  id: '/course/$slug/learn',
  path: '/course/$slug/learn',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/record': typeof RecordRoute
  '/course/$slug/complete': typeof CourseSlugCompleteRoute
  '/course/$slug/learn': typeof CourseSlugLearnRoute
  '/course/$slug/': typeof CourseSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/record': typeof RecordRoute
  '/course/$slug/complete': typeof CourseSlugCompleteRoute
  '/course/$slug/learn': typeof CourseSlugLearnRoute
  '/course/$slug': typeof CourseSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/record': typeof RecordRoute
  '/course/$slug/complete': typeof CourseSlugCompleteRoute
  '/course/$slug/learn': typeof CourseSlugLearnRoute
  '/course/$slug/': typeof CourseSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/record'
    | '/course/$slug/complete'
    | '/course/$slug/learn'
    | '/course/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/record'
    | '/course/$slug/complete'
    | '/course/$slug/learn'
    | '/course/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/record'
    | '/course/$slug/complete'
    | '/course/$slug/learn'
    | '/course/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  RecordRoute: typeof RecordRoute
  CourseSlugCompleteRoute: typeof CourseSlugCompleteRoute
  CourseSlugLearnRoute: typeof CourseSlugLearnRoute
  CourseSlugIndexRoute: typeof CourseSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$slug/': {
      id: '/course/$slug/'
      path: '/course/$slug'
      fullPath: '/course/$slug/'
      preLoaderRoute: typeof CourseSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$slug/complete': {
      id: '/course/$slug/complete'
      path: '/course/$slug/complete'
      fullPath: '/course/$slug/complete'
      preLoaderRoute: typeof CourseSlugCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$slug/learn': {
      id: '/course/$slug/learn'
      path: '/course/$slug/learn'
      fullPath: '/course/$slug/learn'
      preLoaderRoute: typeof CourseSlugLearnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  RecordRoute: RecordRoute,
  CourseSlugCompleteRoute: CourseSlugCompleteRoute,
  CourseSlugLearnRoute: CourseSlugLearnRoute,
  CourseSlugIndexRoute: CourseSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
